"""Phase 3 - operator identification, Excel import and Maker-Checker validation.

Adds:
  * users.employee_number (matricule) and users.service - an operator is never anonymous;
  * roles.can_validate - which responsibles may check another operator's entry;
  * data_imports / import_rows - uploaded spreadsheets awaiting a decision;
  * maker/checker/decision/source columns on audit_logs.

The two NOT NULL columns are added nullable, backfilled, then constrained, so the
migration also runs on a database that already holds rows.

Revision ID: 0003_maker_checker
Revises: 0002_business_model
Create Date: 2026-08-20 08:57:33.138339
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0003_maker_checker"
down_revision: Union[str, None] = "0002_business_model"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('import_type', sa.Enum('RECEPTION', 'INSPECTION', 'PRODUCTION_REQUEST', name='importtype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('IMPORTED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', name='importstatus', native_enum=False, length=24), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('source_size_bytes', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('valid_row_count', sa.Integer(), nullable=False),
    sa.Column('invalid_row_count', sa.Integer(), nullable=False),
    sa.Column('applied_row_count', sa.Integer(), nullable=False),
    sa.Column('maker_id', sa.Integer(), nullable=False),
    sa.Column('maker_reference', sa.String(length=20), nullable=False),
    sa.Column('maker_role', sa.String(length=32), nullable=False),
    sa.Column('maker_service', sa.String(length=60), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('checker_id', sa.Integer(), nullable=True),
    sa.Column('checker_reference', sa.String(length=20), nullable=True),
    sa.Column('checker_role', sa.String(length=32), nullable=True),
    sa.Column('checker_service', sa.String(length=60), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', name='validationdecision', native_enum=False, length=20), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['checker_id'], ['users.id'], name=op.f('fk_data_imports_checker_id_users')),
    sa.ForeignKeyConstraint(['maker_id'], ['users.id'], name=op.f('fk_data_imports_maker_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_imports'))
    )
    with op.batch_alter_table('data_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_imports_checker_id'), ['checker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_imports_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_imports_import_type'), ['import_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_imports_maker_id'), ['maker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_imports_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_data_imports_source_hash'), ['source_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_imports_status'), ['status'], unique=False)

    op.create_table('import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INVALID', 'APPLIED', 'REJECTED', 'FAILED', name='importrowstatus', native_enum=False, length=16), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_reference', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['data_imports.id'], name=op.f('fk_import_rows_import_id_data_imports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_rows'))
    )
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_rows_import_id'), ['import_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_rows_status'), ['status'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_reference', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('actor_role', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('maker_reference', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('maker_role', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('checker_reference', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('checker_role', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('decision', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('source_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('source_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_reference'), ['actor_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_checker_reference'), ['checker_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_maker_reference'), ['maker_reference'], unique=False)

    # Existing rows default to "cannot validate"; the seed sets the real value.
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "can_validate", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )

    # employee_number is NOT NULL UNIQUE: add it nullable, backfill a deterministic
    # placeholder for any pre-existing operator, then apply the constraint.
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("employee_number", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("service", sa.String(length=60), nullable=True))

    op.execute(
        "UPDATE users SET employee_number = 'EMP-' || substr('0000' || id, -4, 4) "
        "WHERE employee_number IS NULL"
    )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "employee_number", existing_type=sa.String(length=20), nullable=False
        )
        batch_op.create_index(
            batch_op.f("ix_users_employee_number"), ["employee_number"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_users_service"), ["service"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_service'))
        batch_op.drop_index(batch_op.f('ix_users_employee_number'))
        batch_op.drop_column('service')
        batch_op.drop_column('employee_number')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('can_validate')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_maker_reference'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_checker_reference'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_reference'))
        batch_op.drop_column('source_hash')
        batch_op.drop_column('source_file')
        batch_op.drop_column('decision')
        batch_op.drop_column('checker_role')
        batch_op.drop_column('checker_reference')
        batch_op.drop_column('maker_role')
        batch_op.drop_column('maker_reference')
        batch_op.drop_column('actor_role')
        batch_op.drop_column('actor_reference')

    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_rows_status'))
        batch_op.drop_index(batch_op.f('ix_import_rows_import_id'))

    op.drop_table('import_rows')
    with op.batch_alter_table('data_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_imports_status'))
        batch_op.drop_index(batch_op.f('ix_data_imports_source_hash'))
        batch_op.drop_index(batch_op.f('ix_data_imports_reference'))
        batch_op.drop_index(batch_op.f('ix_data_imports_maker_id'))
        batch_op.drop_index(batch_op.f('ix_data_imports_import_type'))
        batch_op.drop_index(batch_op.f('ix_data_imports_decision'))
        batch_op.drop_index(batch_op.f('ix_data_imports_checker_id'))

    op.drop_table('data_imports')
    # ### end Alembic commands ###
