"""Phase 2 - complete business data model.

Suppliers, categories, parts, lots, receptions, inspections, quality validations,
warehouses, locations, part addressing, stock, stock movements, production
stations and requests, audit log, AI recommendations and system settings.

Original message: phase2 business data model

Revision ID: 0002_business_model
Revises: 0001_baseline
Create Date: 2026-08-19 16:57:00.259596
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0002_business_model"
down_revision: Union[str, None] = "0001_baseline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_categories_code'))
    )
    op.create_table('production_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('production_line', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_stations'))
    )
    with op.batch_alter_table('production_stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_stations_code'), ['code'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('RECEPTIONIST', 'QUALITY_INSPECTOR', 'QUALITY_MANAGER', 'WAREHOUSE_OPERATOR', 'STATION_LEADER', 'PRODUCTION_MANAGER', 'LOGISTICS_MANAGER', name='rolename', native_enum=False, length=32), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_code'), ['code'], unique=True)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('code', name=op.f('uq_warehouses_code'))
    )
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('designation', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('size_class', sa.Enum('SMALL', 'LARGE', name='partsize', native_enum=False, length=16), nullable=False),
    sa.Column('reception_tolerance_percent', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('average_daily_consumption', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_parts_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parts'))
    )
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parts_reference'), ['reference'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.ForeignKeyConstraint(['station_id'], ['production_stations.id'], name=op.f('fk_users_station_id_production_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('warehouse_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('zone', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('occupied', sa.Integer(), nullable=False),
    sa.Column('warning_threshold_percent', sa.Float(), nullable=False),
    sa.Column('critical_threshold_percent', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_warehouse_locations_capacity_positive')),
    sa.CheckConstraint('occupied >= 0', name=op.f('ck_warehouse_locations_occupied_non_negative')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_warehouse_locations_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse_locations'))
    )
    with op.batch_alter_table('warehouse_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_locations_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_warehouse_locations_zone'), ['zone'], unique=False)

    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=40), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('quantity_expected', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('quantity_approved', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_INSPECTION', 'INSPECTION_IN_PROGRESS', 'QUALITY_PENDING', 'APPROVED', 'REJECTED', 'RED_CAGE', 'STORED', 'CONSUMED', name='lotstatus', native_enum=False, length=32), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('stored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], name=op.f('fk_lots_location_id_warehouse_locations')),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_lots_part_id_parts')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_lots_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lots'))
    )
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lots_lot_number'), ['lot_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_lots_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('part_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('PRIMARY', 'SECONDARY', name='locationrole', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], name=op.f('fk_part_locations_location_id_warehouse_locations')),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_part_locations_part_id_parts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_part_locations')),
    sa.UniqueConstraint('part_id', 'location_id', name='part_location_unique')
    )
    with op.batch_alter_table('part_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_part_locations_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_locations_part_id'), ['part_id'], unique=False)

    op.create_table('production_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity_requested', sa.Integer(), nullable=False),
    sa.Column('quantity_issued', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'PREPARING', 'READY', 'ISSUED', 'REJECTED', 'CANCELLED', name='productionrequeststatus', native_enum=False, length=24), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('needed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity_issued >= 0', name=op.f('ck_production_requests_request_issued_non_negative')),
    sa.CheckConstraint('quantity_requested > 0', name=op.f('ck_production_requests_request_quantity_positive')),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_production_requests_approved_by_id_users')),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], name=op.f('fk_production_requests_issued_by_id_users')),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_production_requests_part_id_parts')),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_production_requests_requested_by_id_users')),
    sa.ForeignKeyConstraint(['station_id'], ['production_stations.id'], name=op.f('fk_production_requests_station_id_production_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_requests'))
    )
    with op.batch_alter_table('production_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_requests_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_requests_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_production_requests_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_requests_status'), ['status'], unique=False)

    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('last_movement_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity_available >= 0', name=op.f('ck_stock_quantity_non_negative')),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_stock_part_id_parts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock'))
    )
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_part_id'), ['part_id'], unique=True)

    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('SHORTAGE_RISK', 'PRIORITY', 'BLOCKED_LOT', 'WAREHOUSE_SATURATION', 'OPTIMIZATION', name='recommendationkind', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('OK', 'INFO', 'WARNING', 'CRITICAL', name='severity', native_enum=False, length=16), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel', native_enum=False, length=16), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('location_code', sa.String(length=20), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_ai_recommendations_lot_id_lots')),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_ai_recommendations_part_id_parts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_recommendations'))
    )
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_recommendations_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_recommendations_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_recommendations_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_recommendations_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_recommendations_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_recommendations_severity'), ['severity'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('LOT_RECEIVED', 'INSPECTION_STARTED', 'INSPECTION_RECORDED', 'QUALITY_APPROVED', 'QUALITY_REJECTED', 'QUALITY_RED_CAGE', 'RED_CAGE_RELEASED', 'RED_CAGE_SCRAPPED', 'STORAGE_CONFIRMED', 'STOCK_INCREMENTED', 'STOCK_DECREMENTED', 'REQUEST_CREATED', 'REQUEST_SUBMITTED', 'REQUEST_APPROVED', 'REQUEST_REJECTED', 'REQUEST_PREPARING', 'REQUEST_READY', 'REQUEST_ISSUED', 'REQUEST_CANCELLED', 'SETTING_UPDATED', 'SIMULATION_RUN', name='auditaction', native_enum=False, length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_reference', sa.String(length=40), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('location_code', sa.String(length=20), nullable=True),
    sa.Column('status_before', sa.String(length=40), nullable=True),
    sa.Column('status_after', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=120), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_audit_logs_lot_id_lots')),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_audit_logs_part_id_parts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_reference'), ['entity_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_part_id'), ['part_id'], unique=False)

    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('defects_found', sa.Integer(), nullable=False),
    sa.Column('defect_threshold_percent', sa.Float(), nullable=False),
    sa.Column('result', sa.Enum('CONFORM', 'NON_CONFORM', name='inspectionresult', native_enum=False, length=20), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], name=op.f('fk_inspections_inspector_id_users')),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_inspections_lot_id_lots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspections'))
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspections_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_inspections_result'), ['result'], unique=False)

    op.create_table('receptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('quantity_expected', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('quantity_gap', sa.Integer(), nullable=False),
    sa.Column('tolerance_percent_applied', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACCEPTED', 'ACCEPTED_WITH_TOLERANCE', 'QUANTITY_MISMATCH', name='receptionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('delivery_note', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_receptions_lot_id_lots')),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], name=op.f('fk_receptions_received_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receptions')),
    sa.UniqueConstraint('lot_id', name=op.f('uq_receptions_lot_id'))
    )
    with op.batch_alter_table('receptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receptions_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_receptions_status'), ['status'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('movement_type', sa.Enum('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT', name='movementtype', native_enum=False, length=16), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('production_request_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_stock_movements_movement_quantity_positive')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_stock_movements_actor_id_users')),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], name=op.f('fk_stock_movements_location_id_warehouse_locations')),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_stock_movements_lot_id_lots')),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_stock_movements_part_id_parts')),
    sa.ForeignKeyConstraint(['production_request_id'], ['production_requests.id'], name=op.f('fk_stock_movements_production_request_id_production_requests')),
    sa.ForeignKeyConstraint(['station_id'], ['production_stations.id'], name=op.f('fk_stock_movements_station_id_production_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_production_request_id'), ['production_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_reference'), ['reference'], unique=True)

    op.create_table('quality_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'RED_CAGE', name='qualitydecision', native_enum=False, length=20), nullable=False),
    sa.Column('quantity_approved', sa.Integer(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_quality_validations_decided_by_id_users')),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name=op.f('fk_quality_validations_inspection_id_inspections')),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_quality_validations_lot_id_lots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_validations'))
    )
    with op.batch_alter_table('quality_validations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_validations_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_validations_lot_id'), ['lot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_validations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_validations_lot_id'))
        batch_op.drop_index(batch_op.f('ix_quality_validations_decision'))

    op.drop_table('quality_validations')
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_reference'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_production_request_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_part_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_lot_id'))

    op.drop_table('stock_movements')
    with op.batch_alter_table('receptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receptions_status'))
        batch_op.drop_index(batch_op.f('ix_receptions_reference'))

    op.drop_table('receptions')
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspections_result'))
        batch_op.drop_index(batch_op.f('ix_inspections_reference'))
        batch_op.drop_index(batch_op.f('ix_inspections_lot_id'))

    op.drop_table('inspections')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_part_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_lot_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_reference'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_severity'))
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_priority'))
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_part_id'))
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_lot_id'))
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_kind'))
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_is_active'))

    op.drop_table('ai_recommendations')
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_part_id'))

    op.drop_table('stock')
    with op.batch_alter_table('production_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_requests_status'))
        batch_op.drop_index(batch_op.f('ix_production_requests_station_id'))
        batch_op.drop_index(batch_op.f('ix_production_requests_reference'))
        batch_op.drop_index(batch_op.f('ix_production_requests_part_id'))

    op.drop_table('production_requests')
    with op.batch_alter_table('part_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_locations_part_id'))
        batch_op.drop_index(batch_op.f('ix_part_locations_location_id'))

    op.drop_table('part_locations')
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lots_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_lots_status'))
        batch_op.drop_index(batch_op.f('ix_lots_part_id'))
        batch_op.drop_index(batch_op.f('ix_lots_lot_number'))

    op.drop_table('lots')
    with op.batch_alter_table('warehouse_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_locations_zone'))
        batch_op.drop_index(batch_op.f('ix_warehouse_locations_code'))

    op.drop_table('warehouse_locations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parts_reference'))

    op.drop_table('parts')
    op.drop_table('warehouses')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_code'))

    op.drop_table('suppliers')
    op.drop_table('roles')
    with op.batch_alter_table('production_stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_stations_code'))

    op.drop_table('production_stations')
    op.drop_table('categories')
    # ### end Alembic commands ###
