"""Phase 4 - vehicle nomenclature, work zones and full operator identity.

Adds the vehicle BOM (2 000+ synthetic references), the work zone of each
operator and their first/last name. All new columns are nullable, so the
migration runs on a populated database.

Revision ID: 0004_vehicle_bom
Revises: 0003_maker_checker
Create Date: 2026-08-20 09:48:12.257471
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0004_vehicle_bom"
down_revision: Union[str, None] = "0003_maker_checker"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('segment', sa.String(length=60), nullable=True),
    sa.Column('model_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles'))
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_code'), ['code'], unique=True)

    op.create_table('vehicle_bom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('part_reference', sa.String(length=40), nullable=False),
    sa.Column('part_description', sa.String(length=200), nullable=False),
    sa.Column('system_code', sa.String(length=10), nullable=False),
    sa.Column('system_label', sa.String(length=80), nullable=False),
    sa.Column('subsystem', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('size_class', sa.Enum('SMALL', 'LARGE', name='partsize', native_enum=False, length=16), nullable=False),
    sa.Column('quantity_per_vehicle', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('supplier_code', sa.String(length=20), nullable=True),
    sa.Column('is_managed', sa.Boolean(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_vehicle_bom_part_id_parts')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_vehicle_bom_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_bom')),
    sa.UniqueConstraint('vehicle_id', 'part_reference', name='bom_vehicle_reference_unique')
    )
    with op.batch_alter_table('vehicle_bom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_bom_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_bom_is_managed'), ['is_managed'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_bom_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_bom_part_reference'), ['part_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_bom_supplier_code'), ['supplier_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_bom_system_code'), ['system_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_bom_vehicle_id'), ['vehicle_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('zone', sa.Enum('RECEPTION', 'INSPECTION', 'QUALITY', 'WAREHOUSE', 'PRODUCTION', 'LOGISTICS', name='zone', native_enum=False, length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_zone'), ['zone'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_zone'))
        batch_op.drop_column('zone')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('vehicle_bom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_bom_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_bom_system_code'))
        batch_op.drop_index(batch_op.f('ix_vehicle_bom_supplier_code'))
        batch_op.drop_index(batch_op.f('ix_vehicle_bom_part_reference'))
        batch_op.drop_index(batch_op.f('ix_vehicle_bom_part_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_bom_is_managed'))
        batch_op.drop_index(batch_op.f('ix_vehicle_bom_category'))

    op.drop_table('vehicle_bom')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_code'))

    op.drop_table('vehicles')
    # ### end Alembic commands ###
